apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: webapp
spec:
  selector:
    matchLabels:
      mylabelname: webapp
  replicas: 2  #kubernetes will away make Pod running for 2 Pod
  template: 
    metadata:
      labels: 
        mylabelname: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0-5

---
apiVersion: v1
kind: Pod
metadata:
  name: queue
  labels: 
    app: queue
spec:
  containers:
    - name: queue
      image: richardchesterwood/k8s-fleetman-queue:release1

#Service => expose Pod, make pod to aviable to call from external cluster
#pod => wrapped container and running image
#replicaset => Takecare Pod, when Pod down or not avaible replicaset will create new one.
              # so we need to set how manay Pod we need on 'replicas' option
              # and replicaset will guaruntee that our service will aviable