apiVersion: v1
kind: Service
metadata:
  name: fleetman-webapp

spec:
  #This defindes which port are going to be represented by this service
  selector:
    # mylabelname is manual name, you can use any name but the name must be match with Pod config belong to labels tag 
    mylabelname: webapp
    
  ports:
    - name: http
      port: 80 # port 80 will expose to nodePort that is 30080
      nodePort: 30080 #nodePort must be grater than 30000 that is rule

  #We got two choice for type, ClusterIP and NodePort
  # ClusterIP is only access internal Cluster
  # NoertPort is exposes service to external Cluster
  type: NodePort
  

---

apiVersion: v1
kind: Service
metadata:
  name: fleetman-queue

spec:
  selector:
    app: queue

  ports:
    - name: http
      port: 8161
      nodePort: 30010
      
  type: NodePort

